[build]
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"


[functions]
  external_node_modules = []
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
